"""add category parent_id for subcategories

Revision ID: 5226feb3527f
Revises: aab50b75bdb3
Create Date: 2026-08-23 19:17:16.001384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5226feb3527f'
down_revision: Union[str, None] = 'aab50b75bdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_categories_parent_id_categories'), 'categories', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_parent_id_categories'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
